### ISSUE TITLE
bug: "Next" & "Prev" button functionality and also "Jump To" button functionality 

### ISSUE THREAD

**Issue by Om8983** [code100x/daily-code#622]
**Describe the bug**
"Next", "Prev" and "Jump To" functionality isn't working properly.

**To Reproduce**
1. Do something
2. See error

**Expected behavior**
Expected behaviour is very obvious I guess. 

**Screenshots or GIFs**
IDK how to paste the ss rather you should experience yourself.

**Info (please complete the following information):**

**Additional context**

https://github.com/user-attachments/assets/3e15b247-5815-4633-8ffd-bb4ebd38e6c1

**Comment by SarveshK16** [comment]
I believe this is fixed in the upcoming new UI redesign.

**Comment by SarveshK16** [comment]
@Om8983 can you please recheck locally, because I checked for this specific track just now & I can see the functionality is working fine. Below is the video capture for context. 

https://github.com/user-attachments/assets/433de6bb-8c03-42ce-9db7-b6e5d6f08d8a

**Comment by Om8983** [comment]
Yeah, its fine now. Working on my side as well. Thanks for the assistance

**Comment by Om8983** [comment]
wait is the updated version released cuz the error still persist

**Comment by SarveshK16** [comment]
@Om8983 It's not yet released, hence I asked you to check in local.

**Comment by Om8983** [comment]
okk, fine then. BTW when is it gonna release?? If i may ask....

**Comment by SarveshK16** [comment]
Only Harkirat, Sargam knows the date!
